### PR TITLE
Chinwe 84

### PR DESCRIPTION
**Pull request by ChinweCodes**

### CODE REVIEW

**Review by AndrewGerberBSU — COMMENTED** [review]
have we decided on if we want the checkbox in the dropdown even if it doesnt work?

**Comment by ChinweCodes** [comment]
It still displays the calendar and budget. Just that when you click on the display, it doesn't respond like when it's not in the menu.

**Review by Cloud9-Sec — CHANGES_REQUESTED** [review]
I can approve once the list functionality is working 100%. I don't want to approve if there is a bug still to be resolved.

**Comment by ChinweCodes** [comment]
Well, I explained it on discord yesterday why it can't work properly when it's in a menu tag and you tried working on it too and it didn't work. We would have to let Dr. Walters know.

**Comment by Cloud9-Sec** [comment]
That's fine, we can let her know tomorrow it isn't a possibility to have both. If she decides to roll back that change, we can close this PR out without implementation.

**Pull request closed without merging**
