### PR TITLE
Tool tip

### PR DESCRIPTION
**Pull request by ChinweCodes**

### CODE REVIEW

**Comment by AndrewGerberBSU** [comment]
It seems the input fields have become shorter. Was this intended? We should discuss with @snakeround if we should keep the input fields the same length.

Also, some of the tooltips don't appear in the right direction, they go off-screen.

Furthermore, I don't see the following tooltips:
- Hppd calculations
- Staff type
- Quantity
- Shift
- Shift Total

**Review by AndrewGerberBSU — CHANGES_REQUESTED** [review]
It seems the input fields have become shorter. Was this intended? We should discuss with @snakeround if we should keep the input fields the same length.

Also, some of the tooltips don't appear in the right direction, they go off-screen.

Furthermore, I don't see the following tooltips:
- Hppd calculations

**Review by Cloud9-Sec — CHANGES_REQUESTED** [review]
Reviewed code and found the following needs to be changed prior to merging/next review:

1. Hospital Unit Tooltip appears outside the screen.
2. The input fields have been significantly reduced. This needs to be reverted back to the original size.

**Review by Cloud9-Sec — CHANGES_REQUESTED** [review]
ToolTip is also still appearing off screen:
image

**Review by snakeround — APPROVED** [review]

**Review by AndrewGerberBSU — APPROVED** [review]
Changes look great, thanks for fixing it!

**Review by Cloud9-Sec — APPROVED** [review]

**Pull request merged**
